### ISSUE TITLE
Chen_data_old   to interpolated_center_24632to38235_part2.csv

### ISSUE THREAD

**Issue by Kavato** [cd-wang/RAIDS#2]
Hello!
I apologize in advance for possibly stupid questions.
But how to get the necessary CSV files from a dataset?
For example, “interpolated_center_24632to38235_part2.csv” in chen_data_old, which is then used to create .npy files that are used to train the model.
It’s just that I’ve never worked with such data types before.
If it’s not difficult for you, can you send a code for this?
Thank you so much for sending the previous code.

**Comment by Kavato** [comment]
In file interpolated_center_24632to38235_part2.csv  filename=center/(...)img How can i get this image from raw dataset?

**Comment by cd-wang** [comment]
Hello. 
For such questions, I suggest that you could ask maintainers of respective datasets for the answers. For example, the GitHub repo for Chen_data_old and Chen_data_new is at https://github.com/SullyChen/driving-datasets

**Comment by Kavato** [comment]
I just don’t understand how you made the data csv files and processed the data to them to start learning the network

**Comment by Kavato** [comment]
I really want to teach the network by your code, but I do not have such experience in programming (

**Comment by Kavato** [comment]
I apologize in advance but can you help me?
You somehow got these files and processed the data, is there really no source left?
I would really appreciate your help

**Comment by cd-wang** [comment]
Hello.
You can download the datasets in the zip format from the two links shown at https://github.com/SullyChen/driving-datasets. When you unzip either file, a folder would be generated with a number of images and a text file called data.txt. The data.txt is the original csv file that has the image name and corresponding genuine angle. To convert the original csv file to, say, interpolated_center_24632to38235_part2.csv, you just need to write a simple script either in bash shell or python (you can also use C/C++/Java if you like). A for loop in which every line is processed would form the main body of the script. How to generate intrusions to steering angles has been shown in the Table 1 of our paper (available at https://asset-group.github.io/papers/ICICS19-RAIDS.pdf ). If you need help in writing the script, you could raise a question in https://stackoverflow.com and many programmers would be willing to offer a hand. Otherwise, you could just use the csv files found in the repo for training and testing. 
Hope this resolves your problem.
